[book]
title = "Asynchronous Programming in Rust"
authors = ["Taylor Cramer"]

[build]
create-missing = false

[preprocess.links]

[output.html]
git-repository-url = "https://fourstacks.space/rust-async-book"
site-url = "/rust-async-book/"

[output.linkcheck]
optional=true
follow-web-links = true
traverse-parent-directories = false
